# Generated by Django 4.2.2 on 2023-06-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio_act',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('cedulaRUC', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Socio_act',
                'verbose_name_plural': 'Socios_act',
                'ordering': ['id'],
            },
        ),
    ]
